Add SECURITY.md file
jboss-modules/jboss-modules pull request #296
Opened 2022-11-04 15:16 UTC by Skyllarr

2022-11-08 21:26 UTC, dmlloyd requested changes

2022-11-08 21:26 UTC, dmlloyd commented on SECURITY.md
> +￼Jboss Modules community takes security very seriously, and we aim to take immediate action to address serious security-related problems that involve our products or services.
The spelling should be `JBoss` here.

2022-11-08 22:24 UTC, Skyllarr commented on SECURITY.md
> +￼Jboss Modules community takes security very seriously, and we aim to take immediate action to address serious security-related problems that involve our products or services.
@dmlloyd Fixed. Thank you

2022-11-09 15:16 UTC, dmlloyd approved these changes

2022-11-09 15:16 UTC, merged